# Generated by Django 3.0 on 2020-02-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developershub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developershubblog',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
