# Generated by Django 3.0 on 2020-03-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developershub', '0002_auto_20200227_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopersHubBlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developershub.DevelopersHubBlog')),
            ],
        ),
    ]
