# Generated by Django 3.0 on 2020-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developershub', '0003_developershubblogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='developershubblog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
