# Generated by Django 3.0 on 2020-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingblog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
